blank_lines_lower_bound = 1
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Upper"
max_width = 100
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
