environment_image = "junction_twoway"
environment = "./config/simulations/Intersection/environment.yaml"
formation_group = "./config/simulations/Intersection/formation.ron"

[visualisation.height]
objects = 0.5
height-map = 1.0

[visualisation.draw]
robots = true
communication-graph = false
predicted-trajectories = true
waypoints = true
uncertainty = false
paths = false
communication-radius = false
obstacle-factors = false
tracking = false
interrobot-factors = false
interrobot-factors-safety-distance = false
generated-map = true
sdf = false
robot-colliders = false
environment-colliders = false
robot-robot-collisions = false
robot-environment-collisions = false

[visualisation.uncertainty]
max-radius = 2.5
scale = 30.0

[interaction]
ui-focus-cancels-inputs = true
default-cam-distance = 200.0

[gbp]
sigma-pose-fixed = 0.0000000000000010000000036274937
sigma-factor-dynamics = 0.10000000149011612
sigma-factor-interrobot = 0.009999999776482582
sigma-factor-obstacle = 0.009999999776482582
sigma-factor-tracking = 0.009999999776482582
lookahead-multiple = 3
variables = 10

[gbp.tracking]
switch-padding = 1.0
attraction-distance = 2.0

[gbp.iteration-schedule]
internal = 10
external = 10
schedule = "interleave-evenly"

[gbp.factors-enabled]
dynamic = true
interrobot = true
obstacle = true
tracking = false

[robot]
planning-horizon = 5.0
target-speed = 5.0
inter-robot-safety-distance-multiplier = 2.5

[robot.radius]
min = 1.0
max = 1.0

[robot.communication]
radius = 20.0
failure-rate = 0.0

[simulation]
max-time = 10000.0
time-scale = 4.0
manual-step-factor = 1
hz = 10.0
prng-seed = 2
pause-on-spawn = false
despawn-robot-when-final-waypoint-reached = true
exit-application-on-scenario-finished = false

[rrt]
max-iterations = 5000000
step-size = 5.0
collision-radius = 3.0
neighbourhood-radius = 8.0

[rrt.smoothing]
enabled = true
max-iterations = 500
step-size = 0.5

[graphviz]
export-location = "./assets/export/"

[graphviz.interrobot.active]
style = "dashed"
len = 8.0
color = "red"

[graphviz.interrobot.inactive]
style = "dashed"
len = 8.0
color = "gray"

[manual]
timesteps-per-step = 1

[debug.on-variable-clicked]
obstacle = false
dynamic = false
interrobot = false
tracking = false
variable = false
inbox = false
