environment_image = "junction_twoway"
environment       = "./config/simulations/Complex/environment.yaml"
formation_group   = "./config/simulations/Complex/formation.ron"

[visualisation.height]
objects    = 0.5
height-map = 2.0

[visualisation.draw]
robots                             = false
communication-graph                = true
predicted-trajectories             = true
waypoints                          = true
uncertainty                        = false
paths                              = true
communication-radius               = false
obstacle-factors                   = false
tracking                           = true
interrobot-factors                 = false
interrobot-factors-safety-distance = false
generated-map                      = true
sdf                                = false
robot-colliders                    = false
environment-colliders              = false
robot-robot-collisions             = true
robot-environment-collisions       = true

[visualisation.uncertainty]
max-radius = 2.5
scale      = 300.0

[interaction]
ui-focus-cancels-inputs = true
default-cam-distance    = 300.0

[gbp]
sigma-pose-fixed        = 0.0000000000000010000000036274937
sigma-factor-dynamics   = 0.5
sigma-factor-interrobot = 0.009999999776482582
sigma-factor-obstacle   = 0.009999999776482582
sigma-factor-tracking   = 0.30000001192092896
lookahead-multiple      = 3
variables               = 10

[gbp.tracking]
switch-padding      = 5.0
attraction-distance = 1.0

[gbp.iteration-schedule]
internal = 10
external = 10
schedule = "interleave-evenly"

[gbp.factors-enabled]
dynamic    = true
interrobot = true
obstacle   = true
tracking   = false

[robot]
planning-horizon                       = 5.0
target-speed                           = 7.0
inter-robot-safety-distance-multiplier = 3.200000047683716

[robot.radius]
min = 2.0
max = 2.0

[robot.communication]
radius       = 20.0
failure-rate = 0.0

[simulation]
max-time                                  = 10000.0
time-scale                                = 1.0
manual-step-factor                        = 1
hz                                        = 10.0
prng-seed                                 = 2
pause-on-spawn                            = true
despawn-robot-when-final-waypoint-reached = true
exit-application-on-scenario-finished     = false

[rrt]
max-iterations       = 5000000
step-size            = 5.0
collision-radius     = 3.0
neighbourhood-radius = 8.0

[rrt.smoothing]
enabled        = true
max-iterations = 500
step-size      = 0.5

[graphviz]
export-location = "./assets/export/"

[graphviz.interrobot.active]
style = "dashed"
len   = 8.0
color = "red"

[graphviz.interrobot.inactive]
style = "dashed"
len   = 8.0
color = "gray"

[manual]
timesteps-per-step = 1

[debug.on-variable-clicked]
obstacle   = true
dynamic    = false
interrobot = false
tracking   = true
variable   = true
inbox      = true
