formations:

# Formation 1
- repeat:
    every:
      secs: 5
      nanos: 0
    times: !finite 1
  delay:
    secs: 0
    nanos: 0
  robots: 1
  planning-strategy: only-local
  initial-position:
    shape: !line-segment
    - x: 0.15
      y: 0.1
    - x: 0.15
      y: 0.1
    placement-strategy: !random
      attempts: 1000
  waypoints:
  - shape: !line-segment
    - x: 0.925
      y: 0.785
    - x: 0.925
      y: 0.785
    projection-strategy: identity
  waypoint-reached-when-intersects:
    distance: robot-radius
    intersects-with: horizon
  finished-when-intersects:
    distance: robot-radius
    intersects-with: current

# - repeat:
#     every:
#       secs: 5
#       nanos: 0
#     times: !finite 10
#   delay:
#     secs: 2
#     nanos: 0
#   robots: 1
#   planning-strategy: rrt-star
#   initial-position:
#     shape: !line-segment
#     - x: 0.85
#       y: 0.80
#     - x: 0.85
#       y: 0.8
#     placement-strategy: !random
#       attempts: 1000
#   waypoints:
#   - shape: !line-segment
#     - x: 0.15
#       y: 0.20
#     - x: 0.15
#       y: 0.2
#     projection-strategy: identity
#   waypoint-reached-when-intersects: horizon
#
#
# - repeat:
#     every:
#       secs: 5
#       nanos: 0
#     times: !finite 10
#   delay:
#     secs: 0
#     nanos: 0
#   robots: 1
#   planning-strategy: rrt-star
#   initial-position:
#     shape: !line-segment
#     - x: 0.15
#       y: 0.80
#     - x: 0.15
#       y: 0.8
#     placement-strategy: !random
#       attempts: 1000
#   waypoints:
#   - shape: !line-segment
#     - x: 0.85
#       y: 0.2
#     - x: 0.85
#       y: 0.2
#     projection-strategy: identity
#   waypoint-reached-when-intersects: horizon
#
#
# - repeat:
#     every:
#       secs: 5
#       nanos: 0
#     times: !finite 10
#   delay:
#     secs: 0
#     nanos: 0
#   robots: 1
#   planning-strategy: rrt-star
#   initial-position:
#     shape: !line-segment
#     - x: 0.85
#       y: 0.2
#     - x: 0.85
#       y: 0.2
#     placement-strategy: !random
#       attempts: 1000
#   waypoints:
#   - shape: !line-segment
#     - x: 0.15
#       y: 0.80
#     - x: 0.15
#       y: 0.8
#     projection-strategy: identity
#   waypoint-reached-when-intersects: horizon
