# environment = "junction"
environment_image = "circle_cluttered"
environment       = "./config/simulations/Circle/environment.yaml"
formation_group   = "./config/simulations/Circle/formation.ron"

[interaction]
ui-focus-cancels-inputs = true
default-cam-distance    = 250.0

[visualisation.uncertainty]
max-radius = 2.5
scale      = 300.0

[visualisation.height]
objects    = 0.5
height-map = 1.0

[visualisation.draw]
robots                 = true
communication-graph    = false
predicted-trajectories = true
waypoints              = true
uncertainty            = false
paths                  = true
generated-map          = true
# height-map                         = false
sdf                                = true
communication-radius               = false
obstacle-factors                   = true
tracking                           = false
interrobot-factors                 = false
interrobot-factors-safety-distance = false
robot-colliders                    = false
environment-colliders              = true
robot-robot-collisions             = true
robot-environment-collisions       = true

[gbp]
# sigma-pose-fixed        = 0.000000000000001
sigma-pose-fixed        = 1e-15
sigma-factor-dynamics   = 1.0
sigma-factor-interrobot = 0.005
sigma-factor-obstacle   = 0.005
sigma-factor-tracking   = 0.1
# iterations-per-timestep = 10
lookahead-multiple = 1

[gbp.iteration-schedule]
internal = 50
external = 10
schedule = "interleave-evenly"

[robot]
planning-horizon                       = 13.33
max-speed                              = 15.0
inter-robot-safety-distance-multiplier = 2.2

[robot.radius]
min = 2.0
max = 3.0

[robot.communication]
radius       = 50.0
failure-rate = 0.0

[simulation]
# t0                                        = 0.1
max-time           = 10000.0
time-scale         = 1.0
manual-step-factor = 1
hz                 = 10.0
# world-size                                = 100.0
prng-seed                                 = 0
pause-on-spawn                            = false
despawn-robot-when-final-waypoint-reached = true
exit-application-on-scenario-finished     = true

[rrt]
max-iterations       = 1000000
step-size            = 0.5
collision-radius     = 0.1
neighbourhood-radius = 10.0

[rrt.smoothing]
enabled        = true
max-iterations = 500
step-size      = 0.5

[graphviz]
export-location = "./assets/export/"

[graphviz.interrobot.active]
style = "dashed"
len   = 5.0
# color = "green"
color = "#40a02b"

[graphviz.interrobot.inactive]
style = "dashed"
len   = 5.0
color = "#d20f39"
# color = "red"


[manual]
timesteps-per-step = 1
