tiles:
  grid:
  - â–ˆ
  settings:
    tile-size: 100.0
    path-width: 0.1
    obstacle-height: 1.0
    sdf:
      resolution: 200
      expansion: 0.025
      blur: 0.01
obstacles:
# - shape: !circle
#     radius: 0.05
#   translation:
#     x: 0.325
#     y: 0.60125
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !regular-polygon
#     sides: 3
#     radius: 0.1
#   translation:
#     x: 0.1
#     y: 0.8
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !regular-polygon
#     sides: 4
#     radius: 0.1
#   translation:
#     x: 0.3
#     y: 0.8
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !regular-polygon
#     sides: 5
#     radius: 0.1
#   translation:
#     x: 0.5
#     y: 0.8
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !regular-polygon
#     sides: 6
#     radius: 0.1
#   translation:
#     x: 0.7
#     y: 0.8
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !regular-polygon
#     sides: 7
#     radius: 0.1
#   translation:
#     x: 0.9
#     y: 0.8
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !regular-polygon
#     sides: 7
#     radius: 0.15
#   translation:
#     x: 0.2
#     y: 0.2
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !regular-polygon
#     sides: 6
#     radius: 0.2
#   translation:
#     x: 0.8
#     y: 0.3
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
- shape: !regular-polygon
    sides: 4
    radius: 0.0525
  translation:
    x: 0.625
    y: 0.60125
  rotation: 0.0
  tile-coordinates:
    row: 0
    col: 0
- shape: !regular-polygon
    sides: 4
    radius: 0.035
  translation:
    x: 0.44125
    y: 0.57125
  rotation: 0.0
  tile-coordinates:
    row: 0
    col: 0
- shape: !regular-polygon
    sides: 4
    radius: 0.0225
  translation:
    x: 0.4835
    y: 0.428
  rotation: 0.0
  tile-coordinates:
    row: 0
    col: 0
- shape: !rectangle
    width: 0.0875
    height: 0.035
  translation:
    x: 0.589
    y: 0.3965
  rotation: 0.0
  tile-coordinates:
    row: 0
    col: 0
- shape: !triangle
    angles:
      A: 1.22
      B: 1.22
    radius: 0.025
  rotation: 0.0
  translation:
    x: 0.5575
    y: 0.5145
  tile-coordinates:
    row: 0
    col: 0
- shape: !triangle
    angles:
      A: 0.6981317007977318
      B: 1.9198621771937625
    radius: 0.01
  rotation: 5.2
  translation:
    x: 0.38
    y: 0.432
  tile-coordinates:
    row: 0
    col: 0
