formations:
- repeat:
    every:
      secs: 10
      nanos: 0
    times: !finite 1
  delay:
    secs: 1
    nanos: 0
  robots:                                                                                                                         50
  planning-strategy: only-local
  initial-position:
    shape: !circle
      radius: 50.0
      center:
        x: 0.5
        y: 0.5
    placement-strategy: equal
  waypoints:
  - shape: !circle
      radius: 50.0
      center:
        x: 0.5
        y: 0.5
    projection-strategy: cross
  # waypoint-reached-when-intersects: horizon
  # waypoint-reached-when-intersects: current
  # finished-when-intersects: current
  waypoint-reached-when-intersects:
    distance: robot-radius
    intersects-with: horizon
  finished-when-intersects:
    distance: robot-radius
    intersects-with: current
  # waypoint-reached-when-intersects: !variable 5
